//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionProyectoCS.Models.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTACTO
    {
        public int ID_CONTACTO { get; set; }
        public string NOMBRES { get; set; }
        public string APELLIDOS { get; set; }
        public string TELF1 { get; set; }
        public string TELF2 { get; set; }
        public string EXT { get; set; }
        public string EMAIL1 { get; set; }
        public string EMAIL2 { get; set; }
        public bool ACTIVO { get; set; }
        public int ID_CLIENTE { get; set; }
        public int ID_RESPONSABLE { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual RESPONSABLE RESPONSABLE { get; set; }
    }
}
