//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionProyectoCS.Models.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLEADO()
        {
            this.VISITAs = new HashSet<VISITA>();
        }
    
        public int ID_EMPLEADO { get; set; }
        public int ID_CARGO { get; set; }
        public string NOMBRES { get; set; }
        public string APELLIDOS { get; set; }
        public string IDENTIDAD { get; set; }
        public string COLOR { get; set; }
        public string TELEF1 { get; set; }
        public string TELEF2 { get; set; }
        public string EMAIL1 { get; set; }
        public string EMAIL2 { get; set; }
        public string ID_CALENDAR { get; set; }
        public bool ACTIVO { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
    
        public virtual CARGO CARGO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VISITA> VISITAs { get; set; }
    }
}
