//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionProyectoCS.Models.Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GESTIONP_CSEntities : DbContext
    {
        public GESTIONP_CSEntities()
            : base("name=GESTIONP_CSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CARGO> CARGOes { get; set; }
        public virtual DbSet<CATALOGO_ACTIVIDAD> CATALOGO_ACTIVIDAD { get; set; }
        public virtual DbSet<CLIENTE> CLIENTEs { get; set; }
        public virtual DbSet<EMPLEADO> EMPLEADOes { get; set; }
        public virtual DbSet<ESTADO> ESTADOes { get; set; }
        public virtual DbSet<PROYECTO> PROYECTOes { get; set; }
        public virtual DbSet<RESPONSABLE> RESPONSABLEs { get; set; }
        public virtual DbSet<VISITA> VISITAs { get; set; }
        public virtual DbSet<CONTACTO> CONTACTOes { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
    
        public virtual ObjectResult<SpListadoVistasCS_Result> SpListadoVistasCS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SpListadoVistasCS_Result>("SpListadoVistasCS");
        }
    
        public virtual ObjectResult<SpListadoUsuarioDetail_Result> SpListadoUsuarioDetail()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SpListadoUsuarioDetail_Result>("SpListadoUsuarioDetail");
        }
    }
}
