//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionProyectoCS.Models.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGISTRO_MARCA
    {
        public int ID_REGISTRO_MARCA { get; set; }
        public int ID_EMPLEADO { get; set; }
        public System.DateTime FECHA { get; set; }
        public Nullable<System.DateTime> H_ENTE { get; set; }
        public Nullable<System.DateTime> H_SALE { get; set; }
        public Nullable<System.DateTime> H_ENTA { get; set; }
        public Nullable<System.DateTime> H_SALA { get; set; }
        public Nullable<System.DateTime> H_ENTS { get; set; }
        public Nullable<System.DateTime> H_SALS { get; set; }
        public bool ACTIVO { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
    
        public virtual EMPLEADO EMPLEADO { get; set; }
    }
}
